export interface HeroStatus {
  k: string;
  v: string;
}

export interface Hero {
  name: string;
  thesis: string;
  affil: string;
  state: string;
  status: HeroStatus[];
}

export interface Stat {
  v: string;
  k: string;
}

export interface Education {
  d: string;
  i: string;
  p: string;
  c: string;
}

export interface Organisation {
  n: string;
  r: string;
  p: string;
}

export interface About {
  body: string;
  stats: Stat[];
  edu: Education[];
  org: Organisation[];
}

export interface Research {
  n: string;
  title: string;
  period: string;
  status: string;
  venue: string;
  doi?: string;
  stack: string[];
  summary: string;
  eq: string;
  repo: string;
}

export interface Featured {
  name: string;
  sub: string;
  desc: string;
  stack: string[];
  cat: string;
  status: string;
  diagram: "qpp" | "blind" | "qaoa" | "mad";
  repo: string;
  site?: string;
  doi?: string;
}

export interface IndexProject {
  name: string;
  cat: string;
  status: string;
  year: string;
  stack: string;
  repo: string | null;
  doi?: string;
  attr?: string;
}

export interface NotebookEntry {
  date: string;
  tag: string;
  title: string;
  body: string;
}

export interface Currently {
  k: string;
  v: string;
}

/** One planned week. Hand-written, four weeks ahead. */
export interface RoadmapWeek {
  /** ISO date of the Monday, e.g. "2026-09-07". */
  start: string;
  /** Human label, e.g. "Sep 7". */
  label: string;
  /** Project names planned for the week. Empty means nothing committed. */
  projects: string[];
  /** Optional one-line reason or caveat. */
  note?: string;
}

/**
 * Commit counts for one public repo, generated by
 * scripts/generate-activity.mjs and written to src/lib/activity.json.
 * Never hand-edited.
 */
export interface ActivityRepo {
  repo: string;
  /** Commits per week, oldest first, aligned to ActivitySnapshot.weeks. */
  weeks: number[];
  total: number;
}

export interface ActivitySnapshot {
  /** ISO timestamp of the run that produced this file. */
  generated: string;
  /** Week labels, oldest first, e.g. ["Jul 14", ...]. */
  weeks: string[];
  repos: ActivityRepo[];
}

export interface Cert {
  n: string;
  i: string;
  d: string | null;
  l: string | null;
}

export interface Patent {
  id: string;
  title: string;
  filed: string;
  office: string;
}
